version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: sq
      POSTGRES_PASSWORD: sq
      POSTGRES_DB: scripturequest
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
